@php $options = $page['filter_options'] ?? []; @endphp
<form class="filter-panel users-filter-panel" id="users-filter-form" method="GET" action="{{ route('utilisateurs.index') }}" data-options-url="{{ route('utilisateurs.filter-options') }}" aria-label="Rechercher des utilisateurs">
  <div class="form-group"><label for="users-filter-name">Nom ou prénom</label><input class="form-control" id="users-filter-name" name="nom" type="search" maxlength="100" value="{{ request('nom') }}" placeholder="Nom, prénom ou nom complet"></div>
  <div class="form-group"><label for="users-filter-matricule">Matricule</label><input class="form-control" id="users-filter-matricule" name="matricule" type="search" maxlength="30" value="{{ request('matricule') }}" placeholder="Matricule de l’enseignant"></div>
  <div class="form-group"><label for="users-filter-ia">IA</label><select class="form-control" id="users-filter-ia" name="ia_id"><option value="">Toutes les IA</option>@foreach ($options['ias'] ?? [] as $item)<option value="{{ $item['id'] }}" @selected((string) request('ia_id') === (string) $item['id'])>{{ $item['libelle'] }}</option>@endforeach</select></div>
  <div class="form-group"><label for="users-filter-ief">IEF</label><select class="form-control" id="users-filter-ief" name="ief_id" @disabled(!request('ia_id'))><option value="">{{ request('ia_id') ? 'Toutes les IEF' : 'Sélectionner d’abord une IA' }}</option>@foreach ($options['iefs'] ?? [] as $item)<option value="{{ $item['id'] }}" @selected((string) request('ief_id') === (string) $item['id'])>{{ $item['libelle'] }}</option>@endforeach</select></div>
  <div class="form-group"><label for="users-filter-school">Établissement</label><select class="form-control" id="users-filter-school" name="etablissement_id" @disabled(!request('ief_id'))><option value="">{{ request('ief_id') ? 'Tous les établissements' : 'Sélectionner d’abord une IEF' }}</option>@foreach ($options['etablissements'] ?? [] as $item)<option value="{{ $item['id'] }}" @selected((string) request('etablissement_id') === (string) $item['id'])>{{ $item['libelle'] }}</option>@endforeach</select></div>
  <div class="actions-group"><a class="btn-secondary" href="{{ route('utilisateurs.index') }}">Réinitialiser</a></div>
  <p id="users-filter-status" role="status" aria-live="polite" style="grid-column:1/-1;margin:0"></p>
</form>
