@extends('layouts.app')
@section('title','SICORE - Catégories')
@section('content')
<main class="main-content"><header class="topbar"><div class="page-title-wrap"><button class="mobile-menu-btn" type="button" data-sidebar-toggle aria-label="Ouvrir le menu">&#9776;</button><span class="title-icon"><i class="fa-solid fa-layer-group"></i></span><div><h1>Catégories</h1><p>Gestion des catégories rattachées aux corps enseignants</p></div></div></header>
<section class="content-area">
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-error">{{ session('error') }}</div>@endif
  <div class="stats-grid"><article class="stat-card"><div><p class="stat-label">Catégories</p><p class="stat-value">{{ $pagination['total'] }}</p><p class="stat-note">Enregistrements disponibles</p></div><span class="stat-icon green"><i class="fa-solid fa-layer-group"></i></span></article></div>
  <div class="actions-row"><p class="breadcrumb"><a href="{{ route('parametres.index') }}">Paramétrage</a> &gt; Catégories</p><div class="actions-group"><button class="btn-primary" type="button" data-modal-open="categorie-create-modal">+ Nouvelle catégorie</button></div></div>
  <form class="filter-panel" id="categorieFilterForm" method="GET" action="{{ route('parametres.categories.index') }}"><div class="form-group"><label for="categorieSearch">Rechercher</label><input class="form-control" id="categorieSearch" name="search" value="{{ request('search') }}" placeholder="Code ou libellé"></div><div class="form-group"><label for="categorieCorpsFilter">Corps</label><select class="form-control" id="categorieCorpsFilter" name="corps_id"><option value="">Tous les corps</option>@foreach($corpsOptions as $corps)<option value="{{ data_get($corps,'id') }}" @selected((string)request('corps_id')===(string)data_get($corps,'id'))>{{ data_get($corps,'code') }} — {{ data_get($corps,'libelle') }}</option>@endforeach</select></div><div class="actions-group"><a class="btn-secondary" href="{{ route('parametres.categories.index') }}">Réinitialiser</a></div></form>
  @if($error)<div class="alert alert-error">{{ $error }}</div>@endif
  <section class="table-card"><div class="table-card-header"><div><h2>Liste des catégories</h2><p class="table-card-subtitle">{{ $pagination['total'] }} enregistrement{{ $pagination['total']>1?'s':'' }}</p></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Code</th><th>Libellé</th><th>Corps</th><th>Ordre</th><th>Description</th><th class="actions-cell">Actions</th></tr></thead><tbody>
  @forelse($items as $item)<tr><td>{{ data_get($item,'code','—') }}</td><td>{{ data_get($item,'libelle','—') }}</td><td>{{ data_get($item,'corps.code','—') }} — {{ data_get($item,'corps.libelle','—') }}</td><td>{{ data_get($item,'ordre','—') }}</td><td>{{ data_get($item,'description','—')?:'—' }}</td><td class="actions-cell"><button class="icon-action" type="button" data-modal-open="categorie-edit-modal" data-categorie-edit='@json($item)' title="Modifier"><i class="fa-solid fa-pen-to-square"></i></button><form class="inline-form" method="POST" action="{{ route('parametres.categories.destroy',data_get($item,'id')) }}" onsubmit="return confirm('Supprimer cette catégorie ?');">@csrf @method('DELETE')<button class="icon-action delete" type="submit" title="Supprimer"><i class="fa-solid fa-trash-can"></i></button></form></td></tr>
  @empty<tr><td colspan="6" class="empty-message">Aucune catégorie trouvée.</td></tr>@endforelse
  </tbody></table></div><nav class="pagination">@for($page=1;$page<=$pagination['last_page'];$page++)<a class="page-btn {{ $page===$pagination['current_page']?'active':'' }}" href="{{ route('parametres.categories.index',array_merge(request()->except('page'),['page'=>$page])) }}">{{ $page }}</a>@endfor</nav></section>
</section></main>
<x-module-indemnite type="modal" id="categorie-create-modal" title="Créer une catégorie"><form class="teacher-form" method="POST" action="{{ route('parametres.categories.store') }}">@csrf<div class="form-grid form-grid--balanced"><div class="form-group"><label for="categorieCode">Code *</label><input class="form-control" id="categorieCode" name="code" maxlength="50" required></div><div class="form-group"><label for="categorieLibelle">Libellé *</label><input class="form-control" id="categorieLibelle" name="libelle" maxlength="255" required></div><div class="form-group"><label for="categorieCorps">Corps *</label><select class="form-control" id="categorieCorps" name="corps_id" required><option value="">Sélectionner</option>@foreach($corpsOptions as $corps)<option value="{{ data_get($corps,'id') }}">{{ data_get($corps,'code') }} — {{ data_get($corps,'libelle') }}</option>@endforeach</select></div><div class="form-group"><label for="categorieOrdre">Ordre</label><input class="form-control" id="categorieOrdre" name="ordre" type="number" min="0"></div><div class="form-group categorie-description"><label for="categorieDescription">Description</label><textarea class="form-control" id="categorieDescription" name="description" rows="4" maxlength="500"></textarea></div></div><div class="form-actions"><button class="btn-secondary" type="button" data-modal-close>Annuler</button><button class="btn-primary" type="submit">Créer</button></div></form></x-module-indemnite>
<x-module-indemnite type="modal" id="categorie-edit-modal" title="Modifier une catégorie"><form class="teacher-form" id="categorieEditForm" method="POST">@csrf @method('PUT')<div class="form-grid form-grid--balanced"><div class="form-group"><label for="categorieEditCode">Code *</label><input class="form-control" id="categorieEditCode" name="code" maxlength="50" required></div><div class="form-group"><label for="categorieEditLibelle">Libellé *</label><input class="form-control" id="categorieEditLibelle" name="libelle" maxlength="255" required></div><div class="form-group"><label for="categorieEditCorps">Corps *</label><select class="form-control" id="categorieEditCorps" name="corps_id" required>@foreach($corpsOptions as $corps)<option value="{{ data_get($corps,'id') }}">{{ data_get($corps,'code') }} — {{ data_get($corps,'libelle') }}</option>@endforeach</select></div><div class="form-group"><label for="categorieEditOrdre">Ordre</label><input class="form-control" id="categorieEditOrdre" name="ordre" type="number" min="0"></div><div class="form-group categorie-description"><label for="categorieEditDescription">Description</label><textarea class="form-control" id="categorieEditDescription" name="description" rows="4" maxlength="500"></textarea></div></div><div class="form-actions"><button class="btn-secondary" type="button" data-modal-close>Annuler</button><button class="btn-primary" type="submit">Enregistrer</button></div></form></x-module-indemnite>
@endsection
@push('styles')<style>#categorie-create-modal .modal-dialog,#categorie-edit-modal .modal-dialog{width:calc(100% - 32px);max-width:920px}.categorie-description{grid-column:1/-1}</style>@endpush
@push('scripts')<script>(function(){var form=document.getElementById('categorieFilterForm'),search=document.getElementById('categorieSearch'),corps=document.getElementById('categorieCorpsFilter'),timer,url=@json(route('parametres.categories.update',['category'=>'__ID__']));search.addEventListener('input',function(){clearTimeout(timer);timer=setTimeout(function(){form.requestSubmit()},400)});corps.addEventListener('change',function(){form.requestSubmit()});document.querySelectorAll('[data-categorie-edit]').forEach(function(button){button.addEventListener('click',function(){var item=JSON.parse(button.dataset.categorieEdit);document.getElementById('categorieEditForm').action=url.replace('__ID__',item.id);document.getElementById('categorieEditCode').value=item.code||'';document.getElementById('categorieEditLibelle').value=item.libelle||'';document.getElementById('categorieEditCorps').value=item.corps_id||'';document.getElementById('categorieEditOrdre').value=item.ordre??'';document.getElementById('categorieEditDescription').value=item.description||''})})}());</script>@endpush
