<?php

return [
    'paie-etats-presence' => [
        'title' => 'États de présence',
        'icon' => 'EP',
        'breadcrumb' => 'Gestion de la paie > États de présence',
        'objectives' => [
            'Calculer les retenues liees aux absences et aux retards.',
            'Valider l\'etat de presence du mois.',
            'Transmettre l\'etat de presence au traitement de la paie.',
        ],
        'stats' => [
            [
                'label' => 'Enseignants suivis',
                'value' => '1 247',
                'note' => 'Mois courant',
                'icon' => 'EN',
                'color' => 'green',
            ],
            [
                'label' => 'Absences',
                'value' => '86',
                'note' => '12 nouvelles',
                'icon' => 'AB',
                'color' => 'red',
            ],
            [
                'label' => 'Retards',
                'value' => '41',
                'note' => 'Controle IA',
                'icon' => 'RT',
                'color' => 'yellow',
            ],
            [
                'label' => 'Retenues estimees',
                'value' => '2,4M',
                'note' => 'FCFA',
                'icon' => 'FC',
                'color' => 'blue',
            ],
        ],
        'filters' => [
            'Mois',
            'IA',
            'IEF',
        ],
        'actions' => [
            'Nouvel etat',
            'Valider',
            'Transmettre',
        ],
        'columns' => [
            'Enseignant',
            'Mois',
            'IA',
            'IEF',
            'Absences',
            'Retards',
            'Retenue estimee',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Juin 2026',
                'IA Dakar',
                'IEF Dakar Nord',
                '2',
                '1',
                '18 500 FCFA',
                '<span class="badge badge-pending">Brouillon</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button><button class="table-action primary" type="button" data-confirm="Valider cet etat de presence ?" data-success-message="Etat de presence valide.">Valider</button></div>',
            ],
            [
                'Aissatou FALL',
                'Juin 2026',
                'IA Thies',
                'IEF Thies',
                '0',
                '2',
                '5 000 FCFA',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button" data-confirm="Transmettre cet etat de presence au traitement de la paie ?" data-success-message="Etat transmis a la paie.">Transmettre</button></div>',
            ],
            [
                'Ibrahima SOW',
                'Juin 2026',
                'IA Saint-Louis',
                'IEF Saint-Louis',
                '1',
                '0',
                '8 750 FCFA',
                '<span class="badge badge-primary">Transmis</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Fatou GUEYE',
                'Juin 2026',
                'IA Kaolack',
                'IEF Kaolack',
                '3',
                '3',
                '32 000 FCFA',
                '<span class="badge badge-inactive">Rejete</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
        ],
    ],
    'paie-avance-tabaski' => [
        'title' => 'Avance Tabaski',
        'icon' => 'AT',
        'breadcrumb' => 'Gestion de la paie > Avance Tabaski',
        'stats' => [
            [
                'label' => 'Demandes eligibles',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'Statut',
        ],
        'actions' => [
            'Ajouter une avance',
            'Valider',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Montant avance',
            'Periode',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Awa NDIAYE',
                '250 000 FCFA',
                'Tabaski 2026',
                '<span class="badge badge-active">Eligible</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
            [
                'Cheikh BA',
                '200 000 FCFA',
                'Tabaski 2026',
                '<span class="badge badge-pending">En attente</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Mariama SARR',
                '250 000 FCFA',
                'Tabaski 2026',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Exporter</button></div>',
            ],
        ],
    ],
    'paie-retenue-tabaski' => [
        'title' => 'Retenue Tabaski',
        'icon' => 'RT',
        'breadcrumb' => 'Gestion de la paie > Retenue Tabaski',
        'stats' => [
            [
                'label' => 'Retenues planifiees',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'Statut',
        ],
        'actions' => [
            'Nouvelle retenue',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Montant total avance',
            'Montant retenu',
            'Echeances',
            'Solde restant',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Awa NDIAYE',
                '250 000 FCFA',
                '50 000 FCFA',
                '1 / 5',
                '200 000 FCFA',
                '<span class="badge badge-pending">En cours</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Cheikh BA',
                '200 000 FCFA',
                '40 000 FCFA',
                '2 / 5',
                '120 000 FCFA',
                '<span class="badge badge-pending">En cours</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Mariama SARR',
                '250 000 FCFA',
                '250 000 FCFA',
                '5 / 5',
                '0 FCFA',
                '<span class="badge badge-active">Solde</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-retenues-rappel' => [
        'title' => 'Retenues rappel',
        'icon' => 'RR',
        'breadcrumb' => 'Gestion de la paie > Retenues rappel',
        'stats' => [
            [
                'label' => 'Rappels traites',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Type de rappel',
            'Periode',
            'Statut',
        ],
        'actions' => [
            'Nouvelle retenue',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Type de rappel',
            'Montant rappel',
            'Montant retenu',
            'Justification',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Moussa DIOUF',
                'Regularisation indice',
                '120 000 FCFA',
                '30 000 FCFA',
                'Trop-percu',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Ndeye DIOP',
                'Absence regularisee',
                '75 000 FCFA',
                '15 000 FCFA',
                'Echeancier',
                '<span class="badge badge-pending">En attente</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'paie-exemptions' => [
        'title' => 'Exemption d’avance ou de retenue par enseignant',
        'icon' => 'EX',
        'breadcrumb' => 'Gestion de la paie > Exemption par enseignant',
        'stats' => [
            [
                'label' => 'Exemptions',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Type',
            'Periode',
            'Statut',
        ],
        'actions' => [
            'Nouvelle exemption',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Type d\'exemption',
            'Motif',
            'Periode',
            'Piece justificative',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Abdoulaye FAYE',
                'Avance',
                'Situation sociale',
                'Juin 2026',
                'Jointe',
                '<span class="badge badge-pending">A valider</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button><button class="table-action danger" type="button">Rejeter</button></div>',
            ],
            [
                'Fatou KANE',
                'Retenue',
                'Decision administrative',
                'Juin 2026',
                'Jointe',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-travaux-periodiques' => [
        'title' => 'Travaux périodiques',
        'icon' => 'TP',
        'breadcrumb' => 'Gestion de la paie > Travaux périodiques',
        'stats' => [
            [
                'label' => 'Operations',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Type',
            'Statut',
        ],
        'actions' => [
            'Lancer un traitement',
            'Exporter',
        ],
        'columns' => [
            'Traitement',
            'Periode',
            'Lance par',
            'Date',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Preparation paie',
                'Juin 2026',
                'Amina Diallo',
                '20/06/2026',
                '<span class="badge badge-active">Termine</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Controle retenues',
                'Juin 2026',
                'Amina Diallo',
                '21/06/2026',
                '<span class="badge badge-pending">En cours</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Relancer</button></div>',
            ],
        ],
    ],
    'paie-recap-banque' => [
        'title' => 'État récapitulatif par banque',
        'icon' => 'BQ',
        'breadcrumb' => 'Gestion de la paie > Récapitulatif par banque',
        'stats' => [
            [
                'label' => 'Banques',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Banque',
            'Statut',
        ],
        'actions' => [
            'Generer',
            'Exporter',
        ],
        'columns' => [
            'Banque',
            'Enseignants',
            'Total brut',
            'Total retenues',
            'Net a payer',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'BHS',
                '420',
                '182 000 000 FCFA',
                '24 000 000 FCFA',
                '158 000 000 FCFA',
                '<span class="badge badge-active">Pret</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Exporter</button></div>',
            ],
            [
                'CBAO',
                '315',
                '139 000 000 FCFA',
                '18 000 000 FCFA',
                '121 000 000 FCFA',
                '<span class="badge badge-pending">Controle</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-cotisations-sociales' => [
        'title' => 'Cotisations sociales',
        'icon' => 'CS',
        'breadcrumb' => 'Gestion de la paie > Cotisations sociales',
        'stats' => [
            [
                'label' => 'Cotisations',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Organisme',
            'Statut',
        ],
        'actions' => [
            'Calculer',
            'Exporter',
        ],
        'columns' => [
            'Organisme',
            'Base',
            'Taux',
            'Montant',
            'Periode',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'IPRES',
                '485 000 000 FCFA',
                '14%',
                '67 900 000 FCFA',
                'Juin 2026',
                '<span class="badge badge-active">Calcule</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'CSS',
                '485 000 000 FCFA',
                '7%',
                '33 950 000 FCFA',
                'Juin 2026',
                '<span class="badge badge-pending">Controle</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'paie-etat-salaires' => [
        'title' => 'État des salaires',
        'icon' => 'ES',
        'breadcrumb' => 'Gestion de la paie > État des salaires',
        'objectives' => [
            'Calculer le salaire brut.',
        ],
        'helpTitle' => 'Aide : comment le salaire brut est calcule ?',
        'helpText' => 'Le salaire brut est calcule a partir du traitement indiciaire, des indemnites, des elements variables et des eventuels rappels, avant application des retenues sociales, fiscales ou administratives.',
        'stats' => [
            [
                'label' => 'Salaires calcules',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'IEF',
        ],
        'actions' => [
            'Calculer',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Traitement indiciaire',
            'Indemnites',
            'Elements variables',
            'Salaire brut',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                '310 000 FCFA',
                '85 000 FCFA',
                '25 000 FCFA',
                '420 000 FCFA',
                '<span class="badge badge-active">Calcule</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                '295 000 FCFA',
                '78 000 FCFA',
                '0 FCFA',
                '373 000 FCFA',
                '<span class="badge badge-pending">A verifier</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'paie-elements-saisie-dashboard' => [
        'title' => 'Tableau de bord des éléments de saisie',
        'icon' => 'DS',
        'breadcrumb' => 'Gestion de la paie > Eléments de saisie',
        'stats' => [
            [
                'label' => 'Elements saisis',
                'value' => '528',
                'note' => 'Mois courant',
                'icon' => 'ES',
                'color' => 'green',
            ],
            [
                'label' => 'Valides',
                'value' => '391',
                'note' => '74%',
                'icon' => 'OK',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '102',
                'note' => 'A traiter',
                'icon' => 'AT',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetes',
                'value' => '35',
                'note' => 'Correction',
                'icon' => 'RJ',
                'color' => 'red',
            ],
        ],
        'chart' => [
            'Jan',
            'Fev',
            'Mar',
            'Avr',
            'Mai',
            'Juin',
        ],
        'filters' => [
            'Periode',
            'Type',
            'Statut',
        ],
        'actions' => [
            'Nouvel element',
            'Exporter',
        ],
        'columns' => [
            'Date',
            'Type',
            'Enseignant',
            'Montant',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                '21/06/2026',
                'Retenue absence',
                'Mamadou DIOP',
                '18 500 FCFA',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                '22/06/2026',
                'Rappel',
                'Aissatou FALL',
                '42 000 FCFA',
                '<span class="badge badge-pending">En attente</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'paie-generee-ief' => [
        'title' => 'Paie générée par IEF',
        'icon' => 'PI',
        'breadcrumb' => 'Gestion de la paie > Paie générée par IEF',
        'stats' => [
            [
                'label' => 'Total enseignants',
                'value' => '1 247',
                'note' => 'Toutes IEF',
                'icon' => 'EN',
                'color' => 'green',
            ],
            [
                'label' => 'Total brut',
                'value' => '485M',
                'note' => 'FCFA',
                'icon' => 'BR',
                'color' => 'blue',
            ],
            [
                'label' => 'Total retenues',
                'value' => '72M',
                'note' => 'FCFA',
                'icon' => 'RT',
                'color' => 'red',
            ],
            [
                'label' => 'Net a payer',
                'value' => '413M',
                'note' => 'FCFA',
                'icon' => 'NP',
                'color' => 'green',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'IEF',
        ],
        'actions' => [
            'Consulter',
            'Exporter',
        ],
        'columns' => [
            'IEF',
            'Enseignants',
            'Total brut',
            'Total retenues',
            'Net a payer',
            'Statut generation',
            'Actions',
        ],
        'rows' => [
            [
                'IEF Dakar Nord',
                '215',
                '83 000 000 FCFA',
                '12 000 000 FCFA',
                '71 000 000 FCFA',
                '<span class="badge badge-active">Generee</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Consulter</button><button class="table-action " type="button">Exporter</button></div>',
            ],
            [
                'IEF Thies',
                '184',
                '70 000 000 FCFA',
                '9 500 000 FCFA',
                '60 500 000 FCFA',
                '<span class="badge badge-pending">Controle</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Consulter</button></div>',
            ],
        ],
    ],
    'paie-fermeture-periode' => [
        'title' => 'Fermer la période de paie',
        'icon' => 'FP',
        'breadcrumb' => 'Gestion de la paie > Fermeture de période',
        'sensitive' => true,
        'objectives' => [
            'Controler les paies generees avant fermeture.',
            'Verifier les paies non generees.',
            'Verrouiller la periode apres confirmation.',
        ],
        'stats' => [
            [
                'label' => 'Periode en cours',
                'value' => '06/2026',
                'note' => 'Ouverte',
                'icon' => 'PE',
                'color' => 'blue',
            ],
            [
                'label' => 'Paies generees',
                'value' => '1 198',
                'note' => '96%',
                'icon' => 'OK',
                'color' => 'green',
            ],
            [
                'label' => 'Paies non generees',
                'value' => '49',
                'note' => 'A regulariser',
                'icon' => 'NG',
                'color' => 'red',
            ],
            [
                'label' => 'Controles',
                'value' => '7/8',
                'note' => 'Avant fermeture',
                'icon' => 'CT',
                'color' => 'yellow',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'Controle',
        ],
        'actions' => [
            'Verifier',
            'Exporter',
        ],
        'closePeriod' => true,
        'columns' => [
            'Controle',
            'Resultat',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Paies generees',
                '1 198 dossiers',
                '<span class="badge badge-active">Conforme</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Paies non generees',
                '49 dossiers',
                '<span class="badge badge-pending">A verifier</span>',
                '<div class="table-actions-inline"><button class="table-action primary" type="button">Regulariser</button></div>',
            ],
            [
                'Elements rejetes',
                '8 dossiers',
                '<span class="badge badge-inactive">Bloquant</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-edition-salaires-banque' => [
        'title' => 'Édition des salaires par banque',
        'icon' => 'SB',
        'breadcrumb' => 'Gestion de la paie > Salaires par banque',
        'stats' => [
            [
                'label' => 'Editions',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Banque',
            'Statut',
        ],
        'actions' => [
            'Generer',
            'Exporter',
        ],
        'columns' => [
            'Banque',
            'Periode',
            'Nombre agents',
            'Net a payer',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'BHS',
                'Juin 2026',
                '420',
                '158 000 000 FCFA',
                '<span class="badge badge-active">Pret</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Exporter</button></div>',
            ],
            [
                'CBAO',
                'Juin 2026',
                '315',
                '121 000 000 FCFA',
                '<span class="badge badge-pending">Controle</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-bulletins' => [
        'title' => 'Bulletins des salaires',
        'icon' => 'BS',
        'breadcrumb' => 'Gestion de la paie > Bulletins des salaires',
        'stats' => [
            [
                'label' => 'Bulletins',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'Statut',
        ],
        'actions' => [
            'Generer',
            'Exporter',
        ],
        'columns' => [
            'Periode',
            'Enseignant',
            'Matricule',
            'IA',
            'IEF',
            'Net a payer',
            'Statut bulletin',
            'Actions',
        ],
        'rows' => [
            [
                'Juin 2026',
                'Mamadou DIOP',
                'ENS001',
                'IA Dakar',
                'IEF Dakar Nord',
                '402 000 FCFA',
                '<span class="badge badge-active">Disponible</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Telecharger</button><button class="table-action " type="button">Imprimer</button></div>',
            ],
            [
                'Juin 2026',
                'Aissatou FALL',
                'ENS002',
                'IA Thies',
                'IEF Thies',
                '351 000 FCFA',
                '<span class="badge badge-pending">En preparation</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-effectifs-corps' => [
        'title' => 'Effectifs par corps',
        'icon' => 'EC',
        'breadcrumb' => 'Gestion de la paie > Effectifs par corps',
        'objectives' => [
            'Recuperer les agents actifs.',
        ],
        'stats' => [
            [
                'label' => 'Agents actifs',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'chart' => [
            'PC',
            'PE',
            'MA',
            'CE',
            'CF',
            'AD',
        ],
        'filters' => [
            'Periode',
            'IA',
            'Corps',
        ],
        'actions' => [
            'Actualiser',
            'Exporter',
        ],
        'columns' => [
            'Corps',
            'Nombre agents actifs',
            'IA dominante',
            'Evolution',
            'Actions',
        ],
        'rows' => [
            [
                'Professeurs certifies',
                '438',
                'IA Dakar',
                '+4%',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Exporter</button></div>',
            ],
            [
                'Maitres contractuels',
                '512',
                'IA Thies',
                '+2%',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-non-generee' => [
        'title' => 'Paie non générée',
        'icon' => 'NG',
        'breadcrumb' => 'Gestion de la paie > Paie non générée',
        'objectives' => [
            'Identifier les agents ou structures dont la paie mensuelle n\'est pas encore generee.',
            'Valider la paie mensuelle.',
        ],
        'stats' => [
            [
                'label' => 'Dossiers non generes',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Structure',
            'Statut',
        ],
        'actions' => [
            'Regulariser',
            'Valider',
        ],
        'columns' => [
            'Enseignant',
            'Motif',
            'Structure',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Saliou NDIAYE',
                'Indice manquant',
                'IEF Dakar Nord',
                '<span class="badge badge-pending">A regulariser</span>',
                '<div class="table-actions-inline"><button class="table-action primary" type="button">Regulariser</button><button class="table-action " type="button" data-confirm="Valider cette paie mensuelle ?" data-success-message="Paie mensuelle validee.">Valider</button></div>',
            ],
            [
                'Nafi SENE',
                'Affectation incomplete',
                'IEF Thies',
                '<span class="badge badge-inactive">Bloque</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'paie-sommes-percues' => [
        'title' => 'Sommes perçues',
        'icon' => 'SP',
        'breadcrumb' => 'Gestion de la paie > Sommes perçues',
        'stats' => [
            [
                'label' => 'Sommes suivies',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'IA',
            'Statut',
        ],
        'actions' => [
            'Consolider',
            'Exporter',
        ],
        'columns' => [
            'Enseignant',
            'Periode',
            'Brut',
            'Retenues',
            'Net percu',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Juin 2026',
                '420 000 FCFA',
                '18 000 FCFA',
                '402 000 FCFA',
                '<span class="badge badge-active">Verse</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                'Juin 2026',
                '373 000 FCFA',
                '22 000 FCFA',
                '351 000 FCFA',
                '<span class="badge badge-active">Verse</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'credit-delegation' => [
        'title' => 'Délégation de crédit',
        'icon' => 'DC',
        'breadcrumb' => 'Gestion de la paie > Délégation de crédit',
        'objectives' => [
            'Creer une delegation de credit.',
            'Affecter une delegation a un service ou a une structure.',
        ],
        'stats' => [
            [
                'label' => 'Delegations',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Structure',
            'Service',
            'Statut',
        ],
        'actions' => [
            'Nouvelle delegation',
            'Exporter',
        ],
        'columns' => [
            'Structure beneficiaire',
            'Service',
            'Montant alloue',
            'Date',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'IA Dakar',
                'Paie enseignants',
                '85 000 000 FCFA',
                '18/06/2026',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'IA Thies',
                'Indemnites',
                '42 000 000 FCFA',
                '19/06/2026',
                '<span class="badge badge-pending">En attente</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'credit-edition-delegations' => [
        'title' => 'Édition des délégations de crédits',
        'icon' => 'ED',
        'breadcrumb' => 'Gestion de la paie > Édition des délégations de crédits',
        'objectives' => [
            'Definir le montant disponible.',
            'Suivre le montant engage.',
            'Suivre le montant consomme.',
            'Suivre le solde restant.',
        ],
        'stats' => [
            [
                'label' => 'Montant disponible',
                'value' => '420M',
                'note' => 'FCFA',
                'icon' => 'MD',
                'color' => 'green',
            ],
            [
                'label' => 'Montant engage',
                'value' => '310M',
                'note' => 'FCFA',
                'icon' => 'ME',
                'color' => 'blue',
            ],
            [
                'label' => 'Montant consomme',
                'value' => '248M',
                'note' => 'FCFA',
                'icon' => 'MC',
                'color' => 'yellow',
            ],
            [
                'label' => 'Solde restant',
                'value' => '110M',
                'note' => 'FCFA',
                'icon' => 'SR',
                'color' => 'green',
            ],
        ],
        'filters' => [
            'Structure',
            'Periode',
            'Statut',
        ],
        'actions' => [
            'Editer',
            'Exporter',
        ],
        'columns' => [
            'Reference',
            'Structure',
            'Montant disponible',
            'Engage',
            'Consomme',
            'Solde',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'DEL-2026-001',
                'IA Dakar',
                '150 000 000',
                '120 000 000',
                '92 000 000',
                '30 000 000',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'DEL-2026-002',
                'IA Thies',
                '90 000 000',
                '62 000 000',
                '50 000 000',
                '28 000 000',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'credit-edition-engagements' => [
        'title' => 'Édition des engagements',
        'icon' => 'EG',
        'breadcrumb' => 'Gestion de la paie > Édition des engagements',
        'objectives' => [
            'Generer l\'etat des credits utilises pour la paie.',
        ],
        'stats' => [
            [
                'label' => 'Engagements',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Structure',
            'Statut',
        ],
        'actions' => [
            'Export PDF',
            'Export Excel',
        ],
        'columns' => [
            'Periode',
            'Structure',
            'Credit initial',
            'Credit engage',
            'Credit consomme',
            'Solde',
            'Actions',
        ],
        'rows' => [
            [
                'Juin 2026',
                'IA Dakar',
                '150 000 000',
                '120 000 000',
                '92 000 000',
                '30 000 000',
                '<div class="table-actions-inline"><button class="table-action " type="button">PDF</button><button class="table-action " type="button">Excel</button></div>',
            ],
            [
                'Juin 2026',
                'IA Thies',
                '90 000 000',
                '62 000 000',
                '50 000 000',
                '28 000 000',
                '<div class="table-actions-inline"><button class="table-action " type="button">PDF</button><button class="table-action " type="button">Excel</button></div>',
            ],
        ],
    ],
    'indemnites-convocations' => [
        'title' => 'Gestion des convocations',
        'icon' => 'GC',
        'breadcrumb' => 'Gestion des indemnités > Convocations',
        'stats' => [
            [
                'label' => 'Convocations',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Date',
            'Objet',
            'Statut',
        ],
        'actions' => [
            'Nouvelle convocation',
            'Exporter',
        ],
        'columns' => [
            'Enseignant / agent',
            'Objet',
            'Date',
            'Lieu',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Jury examen',
                '28/06/2026',
                'Dakar',
                '<span class="badge badge-active">Envoyee</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                'Atelier national',
                '30/06/2026',
                'Thies',
                '<span class="badge badge-pending">Brouillon</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
        ],
    ],
    'indemnites-services-faits' => [
        'title' => 'Gestion des services faits',
        'icon' => 'SF',
        'breadcrumb' => 'Gestion des indemnités > Services faits',
        'stats' => [
            [
                'label' => 'Services faits',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Mission',
            'Periode',
            'Validation',
        ],
        'actions' => [
            'Nouveau service fait',
            'Exporter',
        ],
        'columns' => [
            'Agent',
            'Mission',
            'Service fait',
            'Date debut',
            'Date fin',
            'Validation',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Jury examen',
                'Oui',
                '28/06/2026',
                '30/06/2026',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                'Atelier national',
                'Partiel',
                '30/06/2026',
                '02/07/2026',
                '<span class="badge badge-pending">A valider</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button></div>',
            ],
        ],
    ],
    'indemnites-pieces-justificatives' => [
        'title' => 'Gestion des pièces justificatives',
        'icon' => 'PJ',
        'breadcrumb' => 'Gestion des indemnités > Pièces justificatives',
        'stats' => [
            [
                'label' => 'Pieces',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Type de piece',
            'Date depot',
            'Statut',
        ],
        'actions' => [
            'Ajouter une piece',
            'Exporter',
        ],
        'columns' => [
            'Agent',
            'Type de piece',
            'Fichier',
            'Date depot',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Ordre de mission',
                'om-001.pdf',
                '21/06/2026',
                '<span class="badge badge-active">Valide</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                'Rapport',
                'rapport-atelier.pdf',
                '22/06/2026',
                '<span class="badge badge-pending">A verifier</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Valider</button><button class="table-action danger" type="button">Rejeter</button></div>',
            ],
        ],
    ],
    'indemnites-accuses-reception' => [
        'title' => 'Gestion des accusés de réception',
        'icon' => 'AR',
        'breadcrumb' => 'Gestion des indemnités > Accusés de réception',
        'stats' => [
            [
                'label' => 'Accuses',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Document',
            'Date reception',
            'Statut',
        ],
        'actions' => [
            'Nouvel accuse',
            'Exporter',
        ],
        'columns' => [
            'Reference',
            'Agent',
            'Document',
            'Date reception',
            'Recu par',
            'Statut',
        ],
        'rows' => [
            [
                'AR-001',
                'Mamadou DIOP',
                'Ordre de mission',
                '22/06/2026',
                'Bureau paie',
                '<span class="badge badge-active">Recu</span>',
            ],
            [
                'AR-002',
                'Aissatou FALL',
                'Rapport',
                '23/06/2026',
                'Cellule indemnite',
                '<span class="badge badge-pending">En attente</span>',
            ],
        ],
    ],
    'indemnites-calcul' => [
        'title' => 'Calcul des indemnités',
        'icon' => 'CI',
        'breadcrumb' => 'Gestion des indemnités > Calcul',
        'stats' => [
            [
                'label' => 'Calculs',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Type indemnite',
            'Statut',
        ],
        'actions' => [
            'Calculer',
            'Exporter',
        ],
        'calculator' => true,
        'columns' => [
            'Agent',
            'Type indemnite',
            'Base de calcul',
            'Montant',
            'Periode',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Jury',
                '3 jours',
                '185 000 FCFA',
                'Juin 2026',
                '<span class="badge badge-active">Calcule</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Aissatou FALL',
                'Deplacement',
                '180 km',
                '72 000 FCFA',
                'Juin 2026',
                '<span class="badge badge-pending">A calculer</span>',
                '<div class="table-actions-inline"><button class="table-action primary" type="button">Calculer</button></div>',
            ],
        ],
    ],
    'indemnites-frais-deplacement' => [
        'title' => 'Gestion des frais de déplacement',
        'icon' => 'FD',
        'breadcrumb' => 'Gestion des indemnités > Frais de déplacement',
        'stats' => [
            [
                'label' => 'Frais',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Mission',
            'Lieu',
            'Statut',
        ],
        'actions' => [
            'Nouveau frais',
            'Exporter',
        ],
        'columns' => [
            'Agent',
            'Mission',
            'Lieu depart',
            'Lieu arrivee',
            'Distance',
            'Montant',
            'Justificatif',
            'Statut',
        ],
        'rows' => [
            [
                'Mamadou DIOP',
                'Jury examen',
                'Dakar',
                'Thies',
                '72 km',
                '45 000 FCFA',
                'Joint',
                '<span class="badge badge-active">Valide</span>',
            ],
            [
                'Aissatou FALL',
                'Atelier',
                'Thies',
                'Saint-Louis',
                '190 km',
                '85 000 FCFA',
                'A joindre',
                '<span class="badge badge-pending">En attente</span>',
            ],
        ],
    ],
    'indemnites-etats-paie' => [
        'title' => 'Génération des états de paie',
        'icon' => 'EP',
        'breadcrumb' => 'Gestion des indemnités > Etats de paie',
        'stats' => [
            [
                'label' => 'Etats generes',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Periode',
            'Type indemnite',
            'Statut',
        ],
        'actions' => [
            'Generer',
            'Exporter',
        ],
        'columns' => [
            'Periode',
            'Type indemnite',
            'Nombre agents',
            'Montant total',
            'Statut generation',
            'Actions',
        ],
        'rows' => [
            [
                'Juin 2026',
                'Jury',
                '82',
                '14 200 000 FCFA',
                '<span class="badge badge-active">Genere</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Exporter</button></div>',
            ],
            [
                'Juin 2026',
                'Deplacement',
                '41',
                '6 450 000 FCFA',
                '<span class="badge badge-pending">En preparation</span>',
                '<div class="table-actions-inline"><button class="table-action primary" type="button">Generer</button></div>',
            ],
        ],
    ],
    'bourses-enregistrer-demande' => [
        'title' => 'Enregistrer une demande',
        'icon' => 'BD',
        'breadcrumb' => 'Gestion des Bourses et aides > Enregistrer une demande',
        'stats' => [
            [
                'label' => 'Demandes',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Type aide',
            'Date',
            'Statut',
        ],
        'actions' => [
            'Nouvelle demande',
            'Exporter',
        ],
        'columns' => [
            'Beneficiaire',
            'Type d\'aide',
            'Montant demande',
            'Motif',
            'Date demande',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Aminata BA',
                'Aide sociale',
                '150 000 FCFA',
                'Appui scolaire',
                '21/06/2026',
                '<span class="badge badge-pending">En attente</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Oumar NDIAYE',
                'Bourse',
                '250 000 FCFA',
                'Formation technique',
                '22/06/2026',
                '<span class="badge badge-active">Complete</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'bourses-valider-dossier' => [
        'title' => 'Valider un dossier',
        'icon' => 'VD',
        'breadcrumb' => 'Gestion des Bourses et aides > Valider un dossier',
        'stats' => [
            [
                'label' => 'Dossiers',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Type aide',
            'Avis',
            'Statut',
        ],
        'actions' => [
            'Valider',
            'Exporter',
        ],
        'columns' => [
            'Beneficiaire',
            'Type aide',
            'Pieces',
            'Avis',
            'Actions',
        ],
        'rows' => [
            [
                'Aminata BA',
                'Aide sociale',
                'Completes',
                'Favorable',
                '<div class="table-actions-inline"><button class="table-action primary" type="button">Valider</button><button class="table-action danger" type="button">Rejeter</button></div>',
            ],
            [
                'Oumar NDIAYE',
                'Bourse',
                'A completer',
                'Reserve',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action danger" type="button">Rejeter</button></div>',
            ],
        ],
    ],
    'bourses-attribuer-aide' => [
        'title' => 'Attribuer une aide',
        'icon' => 'AA',
        'breadcrumb' => 'Gestion des Bourses et aides > Attribuer une aide',
        'stats' => [
            [
                'label' => 'Aides attribuees',
                'value' => '128',
                'note' => 'Période active',
                'icon' => 'fa-solid fa-folder-open',
                'color' => 'green',
            ],
            [
                'label' => 'Validés',
                'value' => '96',
                'note' => '75% traités',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'En attente',
                'value' => '24',
                'note' => 'À suivre',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Rejetés',
                'value' => '8',
                'note' => 'Correction requise',
                'icon' => 'fa-solid fa-circle-xmark',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Aide',
            'Mode paiement',
            'Statut',
        ],
        'actions' => [
            'Attribuer',
            'Exporter',
        ],
        'columns' => [
            'Beneficiaire',
            'Aide validee',
            'Montant attribue',
            'Date attribution',
            'Mode paiement',
            'Statut attribution',
            'Actions',
        ],
        'rows' => [
            [
                'Aminata BA',
                'Aide sociale',
                '150 000 FCFA',
                '23/06/2026',
                'Virement',
                '<span class="badge badge-active">Attribuee</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Oumar NDIAYE',
                'Bourse',
                '250 000 FCFA',
                '23/06/2026',
                'Tresor',
                '<span class="badge badge-pending">En cours</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action primary" type="button">Finaliser</button></div>',
            ],
        ],
    ],
    'utilisateurs' => [
        'title' => 'Utilisateurs',
        'icon' => 'US',
        'breadcrumb' => 'Gestion Utilisateur > Utilisateurs',
        'objectives' => [
            'Consulter les comptes d’accès au système.',
            'Suivre les profils affectés aux utilisateurs.',
            'Garder une vision claire des comptes actifs et suspendus.',
        ],
        'stats' => [
            [
                'label' => 'Comptes',
                'value' => '42',
                'note' => 'Tous profils',
                'icon' => 'fa-solid fa-users',
                'color' => 'green',
            ],
            [
                'label' => 'Actifs',
                'value' => '36',
                'note' => 'Accès ouverts',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'blue',
            ],
            [
                'label' => 'Suspendus',
                'value' => '4',
                'note' => 'À revoir',
                'icon' => 'fa-solid fa-user-lock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Administrateurs',
                'value' => '2',
                'note' => 'Accès sensibles',
                'icon' => 'fa-solid fa-user-shield',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Profil',
            'Service',
            'Statut',
        ],
        'actions' => [
            'Nouvel utilisateur',
            'Exporter',
        ],
        'columns' => [
            'Nom',
            'E-mail',
            'Profil',
            'Service',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Amina Diallo',
                'amina.diallo@sicore.sn',
                'Administrateur',
                'Direction',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Moussa Ndiaye',
                'moussa.ndiaye@sicore.sn',
                'Gestionnaire paie',
                'Paie',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Fatou Kane',
                'fatou.kane@sicore.sn',
                'Contrôleur',
                'Indemnités',
                '<span class="badge badge-suspended">Suspendu</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
    'profils-roles' => [
        'title' => 'Profils / Rôles',
        'icon' => 'PR',
        'breadcrumb' => 'Gestion Utilisateur > Profils / Rôles',
        'objectives' => [
            'Décrire les responsabilités fonctionnelles.',
            'Associer les rôles aux modules SICORE.',
            'Limiter les accès aux besoins réels des services.',
        ],
        'stats' => [
            [
                'label' => 'Profils',
                'value' => '8',
                'note' => 'Rôles actifs',
                'icon' => 'fa-solid fa-id-badge',
                'color' => 'green',
            ],
            [
                'label' => 'Modules couverts',
                'value' => '6',
                'note' => 'Navigation officielle',
                'icon' => 'fa-solid fa-layer-group',
                'color' => 'blue',
            ],
            [
                'label' => 'En revue',
                'value' => '2',
                'note' => 'Validation interne',
                'icon' => 'fa-solid fa-clock',
                'color' => 'yellow',
            ],
            [
                'label' => 'Sensibles',
                'value' => '3',
                'note' => 'Accès renforcés',
                'icon' => 'fa-solid fa-shield-halved',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Module',
            'Niveau',
            'Statut',
        ],
        'actions' => [
            'Nouveau profil',
            'Exporter',
        ],
        'columns' => [
            'Profil',
            'Module principal',
            'Niveau d’accès',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Administrateur',
                'Tous modules',
                'Complet',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
            [
                'Gestionnaire paie',
                'Gestion de la paie',
                'Saisie et validation',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Contrôleur indemnités',
                'Gestion des indemnités',
                'Contrôle',
                '<span class="badge badge-pending">En revue</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button><button class="table-action " type="button">Modifier</button></div>',
            ],
        ],
    ],
    'permissions' => [
        'title' => 'Permissions',
        'icon' => 'PM',
        'breadcrumb' => 'Gestion Utilisateur > Permissions',
        'objectives' => [
            'Visualiser les droits par module.',
            'Séparer les permissions de consultation, saisie, validation et administration.',
            'Préparer les paramètres sans inventer de backend.',
        ],
        'stats' => [
            [
                'label' => 'Permissions',
                'value' => '24',
                'note' => 'Droits définis',
                'icon' => 'fa-solid fa-key',
                'color' => 'green',
            ],
            [
                'label' => 'Lecture',
                'value' => '6',
                'note' => 'Modules',
                'icon' => 'fa-solid fa-eye',
                'color' => 'blue',
            ],
            [
                'label' => 'Validation',
                'value' => '8',
                'note' => 'Processus',
                'icon' => 'fa-solid fa-circle-check',
                'color' => 'yellow',
            ],
            [
                'label' => 'Administration',
                'value' => '4',
                'note' => 'Accès critiques',
                'icon' => 'fa-solid fa-lock',
                'color' => 'red',
            ],
        ],
        'filters' => [
            'Module',
            'Permission',
            'Profil',
        ],
        'actions' => [
            'Nouvelle permission',
            'Exporter',
        ],
        'columns' => [
            'Module',
            'Permission',
            'Profils concernés',
            'Statut',
            'Actions',
        ],
        'rows' => [
            [
                'Gestion de la paie',
                'Valider les salaires',
                'Administrateur, Gestionnaire paie',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Gestion des indemnités',
                'Contrôler les justificatifs',
                'Administrateur, Contrôleur',
                '<span class="badge badge-active">Actif</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
            [
                'Paramétrage',
                'Modifier les référentiels',
                'Administrateur',
                '<span class="badge badge-pending">Restreint</span>',
                '<div class="table-actions-inline"><button class="table-action " type="button">Voir</button></div>',
            ],
        ],
    ],
];
